name: Deploy to Server

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3      
      
    - name: Copy files to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "deploy-TTS-nvidia-nemo/docker-compose.yml"
        target: "/mnt/sdb/Mnemonics/deploy/" 
        
    - name: SSH into server, down container and delete files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /mnt/sdb/Mnemonics/deploy/deploy-TTS-nvidia-nemo   # Change directory
          docker compose down  
          docker compose up -d     
                  